### ISSUE TITLE
sample code does not work.

### ISSUE THREAD

**Issue by jis0324** [scraperapi/scraperapi-code-examples#2]
I followed your [code sample](https://github.com/scraperapi/scraperapi-code-examples/blob/main/Python/Python_Selenium/proxy_port_example.py), but the scraperapi does not work with seleniumwire on python.

```====== WebDriver manager ======
Current google-chrome version is 101.0.4951
Get LATEST chromedriver version for 101.0.4951 google-chrome
Driver [C:\Users\jis0324\.wdm\drivers\chromedriver\win32\101.0.4951.41\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:53580/devtools/browser/0ffd3a3c-12cc-4ffa-8cea-cc04fdeb497b
Traceback (most recent call last):
  File "d:\Work\MyWork\test.py", line 44, in <module>
    driver.get(url)
  File "C:\Users\jis0324\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in get 
    self.execute(Command.GET, {'url': url})
  File "C:\Users\jis0324\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\jis0324\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=101.0.4951.54)
Stacktrace:
Backtrace:
        Ordinal0 [0x00A5B8F3+2406643]
        Ordinal0 [0x009EAF31+1945393]
        Ordinal0 [0x008DC748+837448]
        Ordinal0 [0x008D8EE8+823016]
        Ordinal0 [0x008CE0BD+778429]
        Ordinal0 [0x008CEC9A+781466]
        Ordinal0 [0x008CE2CA+778954]
        Ordinal0 [0x008CD8A6+776358]
        Ordinal0 [0x008CC7C5+772037]
        Ordinal0 [0x008CCC9D+773277]
        Ordinal0 [0x008DDF4A+843594]
        Ordinal0 [0x00934D3D+1199421]
        Ordinal0 [0x0092427C+1131132]
        Ordinal0 [0x00934682+1197698]
        Ordinal0 [0x00924096+1130646]
        Ordinal0 [0x008FE636+976438]
        Ordinal0 [0x008FF546+980294]
        GetHandleVerifier [0x00CC9612+2498066]
        GetHandleVerifier [0x00CBC920+2445600]
        GetHandleVerifier [0x00AF4F2A+579370]
        GetHandleVerifier [0x00AF3D36+574774]
        Ordinal0 [0x009F1C0B+1973259]
        Ordinal0 [0x009F6688+1992328]
        Ordinal0 [0x009F6775+1992565]
        Ordinal0 [0x009FF8D1+2029777]
        BaseThreadInitThunk [0x759AFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77837A7E+286]
        RtlGetAppContainerNamedObjectPath [0x77837A4E+238]```

This is the full error content, and main error is `net::ERR_TUNNEL_CONNECTION_FAILED`

**Comment by khashayar-ghavami** [comment]
@jis0324 Indeed. Doesnt work at all for me whatevery URL I choose or whatever params I set
